export enum ValidateEnum {
  arrayContains = 'arrayContains',
  arrayMaxSize = 'arrayMaxSize',
  arrayMinSize = 'arrayMinSize',
  arrayNotContains = 'arrayNotContains',
  arrayNotEmpty = 'arrayNotEmpty',
  arrayUnique = 'arrayUnique',
  contains = 'contains',
  equals = 'equals',
  isAlpha = 'isAlpha',
  isAlphanumeric = 'isAlphanumeric',
  isArray = 'isArray',
  isAscii = 'isAscii',
  isBase32 = 'isBase32',
  isBase64 = 'isBase64',
  isBIC = 'isBIC',
  isBoolean = 'isBoolean',
  isBooleanString = 'isBooleanString',
  isBtcAddress = 'isBtcAddress',
  isByteLength = 'isByteLength',
  isCreditCard = 'isCreditCard',
  isCurrency = 'isCurrency',
  isDataURI = 'isDataURI',
  isDate = 'isDate',
  isDateString = 'isDateString',
  isDecimal = 'isDecimal',
  isDivisibleBy = 'isDivisibleBy',
  isEAN = 'isEAN',
  isEmail = 'isEmail',
  isEmpty = 'isEmpty',
  isEnum = 'isEnum',
  isEthereumAddress = 'isEthereumAddress',
  IsFirebasePushId = 'IsFirebasePushId',
  isFqdn = 'isFqdn',
  isFullWidth = 'isFullWidth',
  isHalfWidth = 'isHalfWidth',
  isHash = 'isHash',
  isHexadecimal = 'isHexadecimal',
  isHexColor = 'isHexColor',
  isHSL = 'isHSL',
  isIBAN = 'isIBAN',
  isIdentityCard = 'isIdentityCard',
  isIn = 'isIn',
  isInstance = 'isInstance',
  isInt = 'isInt',
  isIp = 'isIp',
  isIsbn = 'isIsbn',
  isIsin = 'isIsin',
  isIso8601 = 'isIso8601',
  isISO31661Alpha2 = 'isISO31661Alpha2',
  isISO31661Alpha3 = 'isISO31661Alpha3',
  isISRC = 'isISRC',
  isISSN = 'isISSN',
  isJson = 'isJson',
  isJwt = 'isJwt',
  isLatitude = 'isLatitude',
  isLatLong = 'isLatLong',
  isLength = 'isLength',
  isLocale = 'isLocale',
  isLongitude = 'isLongitude',
  isLowercase = 'isLowercase',
  isMacAddress = 'isMacAddress',
  isMagnetURI = 'isMagnetURI',
  isMilitaryTime = 'isMilitaryTime',
  isMimeType = 'isMimeType',
  isMongoId = 'isMongoId',
  isMultibyte = 'isMultibyte',
  isNegative = 'isNegative',
  isNotEmpty = 'isNotEmpty',
  isNotEmptyObject = 'isNotEmptyObject',
  isNotIn = 'isNotIn',
  isNumber = 'isNumber',
  isNumberString = 'isNumberString',
  isObject = 'isObject',
  isOctal = 'isOctal',
  isPassportNumber = 'isPassportNumber',
  isPhoneNumber = 'isPhoneNumber',
  isPort = 'isPort',
  isPositive = 'isPositive',
  isPostalCode = 'isPostalCode',
  isRFC3339 = 'isRFC3339',
  isRgbColor = 'isRgbColor',
  isSemVer = 'isSemVer',
  isString = 'isString',
  isSurrogatePair = 'isSurrogatePair',
  isUppercase = 'isUppercase',
  isUrl = 'isUrl',
  isUuid = 'isUuid',
  isVariableWidth = 'isVariableWidth',
  length = 'length',
  matches = 'matches',
  max = 'max',
  maxDate = 'maxDate',
  maxLength = 'maxLength',
  min = 'min',
  minDate = 'minDate',
  minLength = 'minLength',
  notContains = 'notContains',
  notEquals = 'notEquals',
  validator = 'validator',
  isLocalDate = 'isLocalDate',
  isLocalDateTime = 'isLocalDateTime',
  isLocalTime = 'isLocalTime',
}

export const VALIDATE_CONFIG: ValidateEnum[] = [
  ValidateEnum.isNotEmpty,

  ValidateEnum.isString,
  ValidateEnum.isNumber,
  ValidateEnum.isInt,
  ValidateEnum.isBoolean,
  ValidateEnum.isNumberString,
  ValidateEnum.isArray,
  ValidateEnum.isHexColor,
  ValidateEnum.isEnum,
  ValidateEnum.isLocalDate,
  ValidateEnum.isLocalDateTime,
  ValidateEnum.isLocalTime,

  ValidateEnum.arrayNotEmpty,

  ValidateEnum.max,
  ValidateEnum.min,
  ValidateEnum.length,
  ValidateEnum.minLength,
  ValidateEnum.maxLength,

  ValidateEnum.arrayContains,
  ValidateEnum.arrayMaxSize,
  ValidateEnum.arrayMinSize,
  ValidateEnum.arrayNotContains,
  ValidateEnum.arrayUnique,
  ValidateEnum.contains,
  ValidateEnum.equals,
  ValidateEnum.isAlpha,
  ValidateEnum.isAlphanumeric,
  ValidateEnum.isAscii,
  ValidateEnum.isBase32,
  ValidateEnum.isBase64,
  ValidateEnum.isBIC,
  ValidateEnum.isBoolean,
  ValidateEnum.isBooleanString,
  ValidateEnum.isBtcAddress,
  ValidateEnum.isByteLength,
  ValidateEnum.isCreditCard,
  ValidateEnum.isCurrency,
  ValidateEnum.isDataURI,
  ValidateEnum.isDate,
  ValidateEnum.isDateString,
  ValidateEnum.isDecimal,
  ValidateEnum.isDivisibleBy,
  ValidateEnum.isEAN,
  ValidateEnum.isEmail,
  ValidateEnum.isEmpty,
  ValidateEnum.isEthereumAddress,
  ValidateEnum.IsFirebasePushId,
  ValidateEnum.isFqdn,
  ValidateEnum.isFullWidth,
  ValidateEnum.isHalfWidth,
  ValidateEnum.isHash,
  ValidateEnum.isHexadecimal,
  ValidateEnum.isHSL,
  ValidateEnum.isIBAN,
  ValidateEnum.isIdentityCard,
  ValidateEnum.isIn,
  ValidateEnum.isInstance,
  ValidateEnum.isInt,
  ValidateEnum.isIp,
  ValidateEnum.isIsbn,
  ValidateEnum.isIsin,
  ValidateEnum.isIso8601,
  ValidateEnum.isISO31661Alpha2,
  ValidateEnum.isISO31661Alpha3,
  ValidateEnum.isISRC,
  ValidateEnum.isISSN,
  ValidateEnum.isJson,
  ValidateEnum.isJwt,
  ValidateEnum.isLatitude,
  ValidateEnum.isLatLong,
  ValidateEnum.isLength,
  ValidateEnum.isLocale,
  ValidateEnum.isLongitude,
  ValidateEnum.isLowercase,
  ValidateEnum.isMacAddress,
  ValidateEnum.isMagnetURI,
  ValidateEnum.isMilitaryTime,
  ValidateEnum.isMimeType,
  ValidateEnum.isMongoId,
  ValidateEnum.isMultibyte,
  ValidateEnum.isNegative,
  ValidateEnum.isNotEmptyObject,
  ValidateEnum.isNotIn,
  ValidateEnum.isObject,
  ValidateEnum.isOctal,
  ValidateEnum.isPassportNumber,
  ValidateEnum.isPhoneNumber,
  ValidateEnum.isPort,
  ValidateEnum.isPositive,
  ValidateEnum.isPostalCode,
  ValidateEnum.isRFC3339,
  ValidateEnum.isRgbColor,
  ValidateEnum.isSemVer,
  ValidateEnum.isSurrogatePair,
  ValidateEnum.isUppercase,
  ValidateEnum.isUrl,
  ValidateEnum.isUuid,
  ValidateEnum.isVariableWidth,
  ValidateEnum.matches,
  ValidateEnum.maxDate,
  ValidateEnum.minDate,
  ValidateEnum.notContains,
  ValidateEnum.notEquals,
  ValidateEnum.validator,
];

